name: Example workflow
on: push
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd .github
          mkdir index
          wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR647/006/SRR6471006/SRR6471006_1.fastq.gz
          wget ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR647/006/SRR6471006/SRR6471006_2.fastq.gz
      - run: |
          pwd
          ls -la
          ls -la .github
      - name: test.R
        run: |
          docker run -v tests:/tests ghcr.io/juyeongkim/data.table:1.14.2 /tests/test.R hello
